/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Jessele Durán
 */
public class EmpleadoMenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public EmpleadoMenuView(String nombre) throws Exception {
        super("Menú Principal de Empleado");
        initComponents();
        this.nombre = nombre;
        initButtons();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        registrarCitaPreviaButton = new javax.swing.JButton();
        nombreLabel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        registrarMenu = new javax.swing.JMenu();
        verMenu = new javax.swing.JMenu();
        reportesMenu = new javax.swing.JMenu();
        citasReporte = new javax.swing.JMenuItem();
        citasMGeneral = new javax.swing.JMenuItem();
        citasMEspecialista = new javax.swing.JMenuItem();
        cerrrarSesionMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel3.setText("Últimas Transacciones");

        registrarCitaPreviaButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        registrarCitaPreviaButton.setText("Realizar Cita Previa");
        registrarCitaPreviaButton.setActionCommand("CitaPrevia");
        registrarCitaPreviaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarCitaPreviaButtonActionPerformed(evt);
            }
        });

        nombreLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        nombreLabel.setText("Bienvenida, Nombre Apellido");

        menuBar.setAlignmentX(0.9F);

        registrarMenu.setText("Registrar");
        registrarMenu.setActionCommand("3");
        registrarMenu.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        menuBar.add(registrarMenu);

        verMenu.setText("Ver");
        verMenu.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        menuBar.add(verMenu);

        reportesMenu.setText("Reportes");
        reportesMenu.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        citasReporte.setText("Cantidad de Citas");
        citasReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citasReporteActionPerformed(evt);
            }
        });
        reportesMenu.add(citasReporte);

        citasMGeneral.setText("Cantidad de Citas por Médico General");
        citasMGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citasMGeneralActionPerformed(evt);
            }
        });
        reportesMenu.add(citasMGeneral);

        citasMEspecialista.setText("Cantidad de Citas por Médico Especialista");
        citasMEspecialista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citasMEspecialistaActionPerformed(evt);
            }
        });
        reportesMenu.add(citasMEspecialista);

        menuBar.add(reportesMenu);

        cerrrarSesionMenu.setText("Cerrar Sesión");
        cerrrarSesionMenu.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cerrrarSesionMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrrarSesionMenuMouseClicked(evt);
            }
        });
        cerrrarSesionMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrrarSesionMenuActionPerformed(evt);
            }
        });
        menuBar.add(cerrrarSesionMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(registrarCitaPreviaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombreLabel)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registrarCitaPreviaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    private void cerrrarSesionMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrrarSesionMenuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cerrrarSesionMenuActionPerformed

    private void cerrrarSesionMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrrarSesionMenuMouseClicked
        System.exit(0);
    }//GEN-LAST:event_cerrrarSesionMenuMouseClicked

    private void registrarCitaPreviaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarCitaPreviaButtonActionPerformed

    }//GEN-LAST:event_registrarCitaPreviaButtonActionPerformed

    private void citasMGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citasMGeneralActionPerformed

    }//GEN-LAST:event_citasMGeneralActionPerformed

    private void citasMEspecialistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citasMEspecialistaActionPerformed
        // TODO add your handling code here:
        /*ReportesController reporte = new ReportesController();

        String result;
        try {
            result = PDFGenerator.createPDFFromHashMapList(this, reporte.instructoresPorCurso(db), "Profesores con su curso");
            Desktop.getDesktop().open(new File(result));
        } catch (Exception ex) {
            //TODO Añadir error !
        }*/
    }//GEN-LAST:event_citasMEspecialistaActionPerformed

    private void citasReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citasReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_citasReporteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu cerrrarSesionMenu;
    public javax.swing.JMenuItem citasMEspecialista;
    public javax.swing.JMenuItem citasMGeneral;
    public javax.swing.JMenuItem citasReporte;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel nombreLabel;
    public javax.swing.JButton registrarCitaPreviaButton;
    public javax.swing.JMenu registrarMenu;
    public javax.swing.JMenu reportesMenu;
    public javax.swing.JMenu verMenu;
    // End of variables declaration//GEN-END:variables
    public String nombre;
    private void initButtons()
    {
        nombreLabel.setText("Bienvenida, " + nombre);
    }


}
