/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import models.Paciente;

/**
 *
 * @author Mota
 */
public class PacienteVerView extends javax.swing.JFrame {

    /**
     * Creates new form verPacienteView
     */
    public PacienteVerView(Paciente paciente) {
        initComponents();
        this.paciente = paciente;
        initButtons();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JLabel();
        tele = new javax.swing.JLabel();
        apellido = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        registrarConsulta = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        verHistorial = new javax.swing.JButton();
        registrarTratamiento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        nombre.setText("Nombre");

        tele.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tele.setText("Teléfono");

        apellido.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        apellido.setText("Apellido");

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel4.setText("Perfil del Paciente");

        registrarConsulta.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        registrarConsulta.setText("Registrar Consulta");
        registrarConsulta.setActionCommand("RegistrarCosulta");
        registrarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarConsultaActionPerformed(evt);
            }
        });

        cancelarButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cancelarButton.setText("Cancelar");
        cancelarButton.setActionCommand("RegistrarMedicoEsp");

        verHistorial.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        verHistorial.setText("Ver Historial");
        verHistorial.setActionCommand("RegistrarMedicoEsp");
        verHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verHistorialActionPerformed(evt);
            }
        });

        registrarTratamiento.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        registrarTratamiento.setText("Registrar Tratamiento a un Diágnostico");
        registrarTratamiento.setActionCommand("RegistrarMedicoEsp");
        registrarTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarTratamientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tele, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(registrarTratamiento)
                            .addComponent(registrarConsulta)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(verHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registrarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tele, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registrarTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verHistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verHistorialActionPerformed

    private void registrarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarConsultaActionPerformed

    private void registrarTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarTratamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarTratamientoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel apellido;
    public javax.swing.JButton cancelarButton;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel nombre;
    public javax.swing.JButton registrarConsulta;
    public javax.swing.JButton registrarTratamiento;
    public javax.swing.JLabel tele;
    public javax.swing.JButton verHistorial;
    // End of variables declaration//GEN-END:variables
    public Paciente paciente;
    private void initButtons()
    {
        nombre.setText(paciente.getNombre());
        apellido.setText(paciente.getApellido());
        tele.setText(paciente.getTelefono());
    }
}
